### ISSUE TITLE
Undo redacted view

### ISSUE THREAD

**Issue by eduard-sukharev** [fourtonfish/redacted#6]
After I've taken all required screenshots the only way to get back to unredacted view of a page is to reload it which is inconvenient. Can we get Unredacted button in a popup?

**Comment by fourtonfish** [comment]
@eduard-sukharev This is a great idea, thank you for the suggestion!

I added a Reset button in https://github.com/fourtonfish/redacted/commit/f7a6a8679c4eb9ee0c1673e78d514a593f054aab, I'm just waiting for the updated version to show up in Chrome and Firefox before closing the issue.

**Comment by fourtonfish** [comment]
The plugin has been updated.

@eduard-sukharev Thanks, again, and please let me know if you run into any issues.
